### ISSUE TITLE
Rename `*_space` to `*_basis`

### ISSUE THREAD

**Issue by chillenzer** [Mayank447/Pseudo-Spectral-Discretization#10]
We're always acting on the same vector space, so using the word "space" in `input_space` and `output_space` might be misleading. When it's a convenient time (i.e., not in the middle of another PR), we should change this in all the interfaces to `input_basis` and `output_basis`.

**Comment by Mayank447** [comment]
Fixed as in #9

**Comment by chillenzer** [comment]
Okay. I'll update #11 to take this into account.

**Comment by chillenzer** [comment]
This is not yet mainline.
