### ISSUE TITLE
Prefer `np.fft` functions over hand-rolled

### ISSUE THREAD

**Issue by chillenzer** [Mayank447/Pseudo-Spectral-Discretization#6]
We should use [fftfreq](https://numpy.org/devdocs/reference/generated/numpy.fft.fftfreq.html#numpy.fft.fftfreq) and [fftshift](https://numpy.org/devdocs/reference/generated/numpy.fft.fftshift.html#numpy.fft.fftshift) instead of hand-rolling the eigenvalues of free derivatives.

**Comment by Mayank447** [comment]
Resolved in #9

**Comment by Mayank447** [comment]
Also just for reference, we don't really require fftshift based on the DFT Matrix.
